export const COUNTRIES_LIST_REQUEST = 'COUNTRIES_LIST_REQUEST'
export const COUNTRIES_LIST_SUCCESS = 'COUNTRIES_LIST_SUCCESS'
export const COUNTRIES_LIST_FAIL = 'COUNTRIES_LIST_FAIL'

export const COUNTRY_DETAILS_REQUEST = 'COUNTRY_DETAILS_REQUEST'
export const COUNTRY_DETAILS_SUCCESS = 'COUNTRY_DETAILS_SUCCESS'
export const COUNTRY_DETAILS_FAIL = 'COUNTRY_DETAILS_FAIL'
